server:
  port: 80

spring:
  application:
    name: hotpack

  datasource:
    url: jdbc:log4jdbc:oracle:thin:@xci.iptime.org:1521/xepdb1
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: ${DB_USERNAME}  # .env의 DB_USERNAME 값
    password: ${DB_PASSWORD}  # .env의 DB_PASSWORD 값

  jpa:
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: true
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        use_sql_comments: true
        show_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true
  sql:
    init:
      mode: always
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
          naver:
            client-name: naver
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: http://localhost/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

jwt:
  issuer: ${JWT_ISSUER}       # .env의 JWT_ISSUER 값
  secret_key: ${JWT_SECRET_KEY}  # .env의 JWT_SECRET_KEY 값
