--INSERT INTO article (title, content, author, created_at, updated_at, nickname) VALUES ('제목1', '내용1', 'user1', sysdate, sysdate, 'nick1')
--INSERT INTO article (title, content, author, created_at, updated_at, nickname) VALUES ('제목2', '내용2', 'user2', sysdate, sysdate, 'nick2')
--INSERT INTO article (title, content, author, created_at, updated_at, nickname) VALUES ('제목3', '내용3', 'user3', sysdate, sysdate, 'nick3')
